[package]
name = "golem-wit"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "WIT definitions and WASI adapter modules for Golem"

[lib]
path = "src/lib.rs"
